version: "3.8"

services:
  db:
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      POSTGRES_USER: justarone
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ~/hdd/data:/var/lib/postgresql/data
