version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: justarone
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ~/hdd/data:/var/lib/postresql/data
